(in-package #:schema-protocol-xsd)

(defconstant +xsd-ns+ "http://www.w3.org/2001/XMLSchema")

(defstruct (xml-elem (:conc-name xe-))
  (name "" :type string)
  (attrs nil)
  (children nil))

(defun local-name (name)
  (let ((pos (position #\: name)))
    (if pos (subseq name (1+ pos)) name)))

(defun xe-attr (elem name &optional default)
  (let ((pair (assoc name (xe-attrs elem) :test #'string-equal)))
    (if pair (cdr pair) default)))

(defun xe-local (elem)
  (local-name (xe-name elem)))

(defun xe-named-p (elem name)
  (and (xml-elem-p elem)
       (string= (xe-local elem) name)))

(defun xe-kids (elem name)
  (loop for c in (xe-children elem)
        when (and (xml-elem-p c) (string= (xe-local c) name))
          collect c))

(defun xe-kid (elem name)
  (find-if (lambda (c) (and (xml-elem-p c) (string= (xe-local c) name)))
           (xe-children elem)))

(defun xe-text (elem)
  (with-output-to-string (s)
    (dolist (c (xe-children elem))
      (when (stringp c)
        (write-string c s)))))

(defun xe (name &optional attrs &rest children)
  (make-xml-elem :name name
                 :attrs attrs
                 :children (remove nil children)))

(defun stringify-key (key)
  (etypecase key
    (string key)
    (symbol (string-downcase (symbol-name key)))
    (character (string key))))

;;; serialize ----------------------------------------------------------------

(defun xml-escape (string &key attr)
  (with-output-to-string (s)
    (loop for c across string
          do (case c
               (#\& (write-string "&amp;" s))
               (#\< (write-string "&lt;" s))
               (#\> (write-string "&gt;" s))
               (#\" (write-string (if attr "&quot;" "\"") s))
               (#\' (write-string (if attr "&apos;" "'") s))
               (t (write-char c s))))))

(defun write-indent (stream n)
  (dotimes (i n)
    (write-string "  " stream)))

(defun write-xml (elem stream &optional (indent 0))
  (write-indent stream indent)
  (write-char #\< stream)
  (write-string (xe-name elem) stream)
  (dolist (pair (xe-attrs elem))
    (write-char #\Space stream)
    (write-string (car pair) stream)
    (write-string "=\"" stream)
    (write-string (xml-escape (princ-to-string (cdr pair)) :attr t) stream)
    (write-char #\" stream))
  (let ((kids (xe-children elem)))
    (cond
      ((null kids)
       (write-string "/>" stream)
       (write-char #\Newline stream))
      ((and (= 1 (length kids)) (stringp (first kids)))
       (write-char #\> stream)
       (write-string (xml-escape (first kids)) stream)
       (write-string "</" stream)
       (write-string (xe-name elem) stream)
       (write-string ">" stream)
       (write-char #\Newline stream))
      (t
       (write-char #\> stream)
       (write-char #\Newline stream)
       (dolist (k kids)
         (if (stringp k)
             (unless (every #'whitespace-char-p k)
               (write-indent stream (1+ indent))
               (write-string (xml-escape k) stream)
               (write-char #\Newline stream))
             (write-xml k stream (1+ indent))))
       (write-indent stream indent)
       (write-string "</" stream)
       (write-string (xe-name elem) stream)
       (write-string ">" stream)
       (write-char #\Newline stream)))))

(defun serialize-xml (elem &key (declaration t))
  (with-output-to-string (s)
    (when declaration
      (write-string "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" s)
      (write-char #\Newline s))
    (write-xml elem s 0)))

;;; parse --------------------------------------------------------------------

(defun whitespace-char-p (c)
  (or (char= c #\Space) (char= c #\Tab) (char= c #\Newline) (char= c #\Return)))

(defun xml-unescape (string)
  (with-output-to-string (s)
    (loop with i = 0
          with n = (length string)
          while (< i n)
          do (let ((c (char string i)))
               (if (char= c #\&)
                   (let ((end (or (position #\; string :start (1+ i)) n)))
                     (let ((ent (subseq string (1+ i) end)))
                       (cond
                         ((string= ent "amp") (write-char #\& s))
                         ((string= ent "lt") (write-char #\< s))
                         ((string= ent "gt") (write-char #\> s))
                         ((string= ent "quot") (write-char #\" s))
                         ((string= ent "apos") (write-char #\' s))
                         ((and (plusp (length ent)) (char= (char ent 0) #\#))
                          (let* ((hex (and (> (length ent) 1) (char= (char ent 1) #\x)))
                                 (code (ignore-errors
                                        (parse-integer ent :start (if hex 2 1)
                                                       :radix (if hex 16 10)))))
                            (if code
                                (write-char (code-char code) s)
                                (write-string (subseq string i (1+ end)) s))))
                         (t (write-string (subseq string i (1+ end)) s))))
                     (setf i (1+ end)))
                   (progn (write-char c s) (incf i)))))))

(defun parse-xml (string)
  (let ((i 0)
        (n (length string)))
    (labels ((peek ()
               (and (< i n) (char string i)))
             (advance ()
               (prog1 (peek) (incf i)))
             (skip-ws ()
               (loop while (and (< i n) (whitespace-char-p (char string i)))
                     do (incf i)))
             (starts-with (lit)
               (and (<= (+ i (length lit)) n)
                    (string= string lit :start1 i :end1 (+ i (length lit)))))
             (skip-until (lit)
               (let ((pos (search lit string :start2 i)))
                 (unless pos
                   (error 'xsd-schema-error :message (format nil "unterminated ~S" lit)))
                 (setf i (+ pos (length lit)))))
             (read-name ()
               (let ((start i))
                 (loop while (and (< i n)
                                  (let ((c (char string i)))
                                    (or (alphanumericp c) (find c "._-:"))))
                       do (incf i))
                 (when (= start i)
                   (error 'xsd-schema-error :message "expected name"))
                 (subseq string start i)))
             (read-quoted ()
               (let ((q (advance)))
                 (unless (or (char= q #\") (char= q #\'))
                   (error 'xsd-schema-error :message "expected quoted attribute"))
                 (let ((start i))
                   (loop while (and (< i n) (char/= (char string i) q))
                         do (incf i))
                   (unless (and (< i n) (char= (char string i) q))
                     (error 'xsd-schema-error :message "unterminated attribute"))
                   (prog1 (xml-unescape (subseq string start i))
                     (incf i)))))
             (read-attrs ()
               (let ((acc '()))
                 (loop
                   (skip-ws)
                   (let ((c (peek)))
                     (when (or (null c) (char= c #\/) (char= c #\>))
                       (return (nreverse acc)))
                     (let ((name (read-name)))
                       (skip-ws)
                       (unless (eql (advance) #\=)
                         (error 'xsd-schema-error :message "expected = in attribute"))
                       (skip-ws)
                       (push (cons name (read-quoted)) acc))))))
             (skip-misc ()
               (loop
                 (skip-ws)
                 (cond
                   ((starts-with "<!--") (skip-until "-->"))
                   ((starts-with "<?") (skip-until "?>"))
                   ((starts-with "<![CDATA[")
                    (return))
                   (t (return)))))
             (read-text ()
               (let ((start i))
                 (loop while (and (< i n) (char/= (char string i) #\<))
                       do (incf i))
                 (xml-unescape (subseq string start i))))
             (read-elem ()
               (skip-misc)
               (unless (eql (advance) #\<)
                 (error 'xsd-schema-error :message "expected '<'"))
               (when (starts-with "![CDATA[")
                 (incf i (length "![CDATA["))
                 (let ((pos (search "]]>" string :start2 i)))
                   (unless pos
                     (error 'xsd-schema-error :message "unterminated CDATA"))
                   (prog1 (subseq string i pos)
                     (setf i (+ pos 3)))))
               (when (char= (peek) #\/)
                 (error 'xsd-schema-error :message "unexpected end tag"))
               (let* ((name (read-name))
                      (attrs (read-attrs)))
                 (skip-ws)
                 (cond
                   ((starts-with "/>")
                    (incf i 2)
                    (make-xml-elem :name name :attrs attrs :children nil))
                   ((eql (peek) #\>)
                    (incf i)
                    (let ((kids '()))
                      (loop
                        (skip-ws)
                        (cond
                          ((null (peek))
                           (error 'xsd-schema-error
                                  :message (format nil "unclosed <~A>" name)))
                          ((starts-with "</")
                           (incf i 2)
                           (let ((end (read-name)))
                             (unless (string= (local-name end) (local-name name))
                               (error 'xsd-schema-error
                                      :message (format nil "end tag ~S vs ~S" end name)))
                             (skip-ws)
                             (unless (eql (advance) #\>)
                               (error 'xsd-schema-error :message "expected '>'")))
                           (return))
                          ((starts-with "<!--")
                           (skip-until "-->"))
                          ((starts-with "<?")
                           (skip-until "?>"))
                          ((char= (peek) #\<)
                           (push (read-elem) kids))
                          (t
                           (let ((text (read-text)))
                             (unless (every #'whitespace-char-p text)
                               (push text kids))))))
                      (make-xml-elem :name name :attrs attrs
                                     :children (nreverse kids))))
                   (t (error 'xsd-schema-error :message "malformed start tag"))))))
      (skip-misc)
      (when (starts-with "<?xml")
        (skip-until "?>")
        (skip-misc))
      (read-elem))))

(defun elem-to-value (elem)
  "XML element → hash-table / string / :null / vector of repeating children."
  (when (or (string-equal (xe-attr elem "nil") "true")
            (string-equal (xe-attr elem "xsi:nil") "true"))
    (return-from elem-to-value :null))
  (let ((elems (remove-if-not #'xml-elem-p (xe-children elem)))
        (texts (remove-if-not #'stringp (xe-children elem))))
    (if (null elems)
        (let ((text (format nil "~{~A~}" texts)))
          text)
        (let ((out (make-hash-table :test #'equal))
              (seen (make-hash-table :test #'equal)))
          (dolist (c elems)
            (let ((k (xe-local c)))
              (incf (gethash k seen 0))))
          (dolist (c elems)
            (let* ((k (xe-local c))
                   (v (elem-to-value c)))
              (if (> (gethash k seen) 1)
                  (let ((acc (gethash k out)))
                    (setf (gethash k out)
                          (if acc
                              (concatenate 'vector acc (vector v))
                              (vector v))))
                  (setf (gethash k out) v))))
          out))))
