(in-package #:schema-protocol-xsd)

;;; Closed XPath 2.0 subset for XSD 1.1 xs:assert / xs:assertion / xs:alternative.
;;;   $value | name | @name | count(name) | string-length(expr) | exists(expr)
;;;   not(expr) | and | or | = eq != ne < lt > gt <= le >= ge
;;; No axes, predicates, functions beyond the above, no namespaces.

(define-condition xpath-error (xsd-schema-error)
  ()
  (:report (lambda (c s)
             (format s "XPath error~@[: ~A~]" (xsd-schema-error-message c)))))

(defun xpath-tokenize (string)
  (let ((i 0)
        (n (length string))
        (toks '()))
    (labels ((peek ()
               (and (< i n) (char string i)))
             (advance ()
               (prog1 (peek) (incf i)))
             (starts (lit)
               (and (<= (+ i (length lit)) n)
                    (string= string lit :start1 i :end1 (+ i (length lit)))
                    (or (= (+ i (length lit)) n)
                        (not (alphanumericp (char string (+ i (length lit))))))))
             (read-name ()
               (let ((start i))
                 (loop while (and (< i n)
                                  (let ((c (char string i)))
                                    (or (alphanumericp c) (find c "_-:"))))
                       do (incf i))
                 (subseq string start i)))
             (read-number ()
               (let ((start i))
                 (when (find (peek) "+-") (advance))
                 (loop while (and (< i n) (or (digit-char-p (char string i))
                                              (char= (char string i) #\.)))
                       do (incf i))
                 (let ((*read-eval* nil))
                   (read-from-string (subseq string start i))))))
      (loop
        (loop while (and (< i n) (whitespace-char-p (char string i)))
              do (incf i))
        (let ((c (peek)))
          (cond
            ((null c) (return (nreverse toks)))
            ((char= c #\$)
             (advance)
             (push (list :var (read-name)) toks))
            ((char= c #\@)
             (advance)
             (push (list :attr (read-name)) toks))
            ((or (char= c #\') (char= c #\"))
             (let ((q (advance))
                   (start i))
               (loop while (and (< i n) (char/= (char string i) q))
                     do (incf i))
               (unless (eql (advance) q)
                 (error 'xpath-error :message "unterminated string"))
               (push (list :string (subseq string start (1- i))) toks)))
            ((or (digit-char-p c) (and (find c "+-") (< (1+ i) n)
                                       (digit-char-p (char string (1+ i)))))
             (push (list :number (read-number)) toks))
            ((starts "and") (incf i 3) (push :and toks))
            ((starts "or") (incf i 2) (push :or toks))
            ((starts "not") (incf i 3) (push :not toks))
            ((starts "eq") (incf i 2) (push :eq toks))
            ((starts "ne") (incf i 2) (push :ne toks))
            ((starts "le") (incf i 2) (push :le toks))
            ((starts "ge") (incf i 2) (push :ge toks))
            ((starts "lt") (incf i 2) (push :lt toks))
            ((starts "gt") (incf i 2) (push :gt toks))
            ((starts "mod") (incf i 3) (push :mod toks))
            ((and (>= (- n i) 2) (string= string "<=" :start1 i :end1 (+ i 2)))
             (incf i 2) (push :le toks))
            ((and (>= (- n i) 2) (string= string ">=" :start1 i :end1 (+ i 2)))
             (incf i 2) (push :ge toks))
            ((and (>= (- n i) 2) (string= string "!=" :start1 i :end1 (+ i 2)))
             (incf i 2) (push :ne toks))
            ((char= c #\=) (advance) (push :eq toks))
            ((char= c #\<) (advance) (push :lt toks))
            ((char= c #\>) (advance) (push :gt toks))
            ((char= c #\() (advance) (push :lparen toks))
            ((char= c #\)) (advance) (push :rparen toks))
            ((char= c #\,) (advance) (push :comma toks))
            ((alpha-char-p c)
             (push (list :name (read-name)) toks))
            (t (error 'xpath-error
                      :message (format nil "unexpected ~S in ~S" c string)))))))))

(defun xpath-parse (string)
  (let* ((toks (xpath-tokenize string))
         (pos 0))
    (labels ((peek ()
               (nth pos toks))
             (next ()
               (prog1 (peek) (incf pos)))
             (eat (want)
               (let ((got (peek)))
                 (unless (eq got want)
                   (error 'xpath-error
                          :message (format nil "expected ~S got ~S" want got)))
                 (next)))
             (name-of (tok)
               (and (consp tok) (eq (first tok) :name) (second tok)))
             (parse-or ()
               (let ((left (parse-and)))
                 (if (eq (peek) :or)
                     (progn (next) `(:or ,left ,(parse-or)))
                     left)))
             (parse-and ()
               (let ((left (parse-cmp)))
                 (if (eq (peek) :and)
                     (progn (next) `(:and ,left ,(parse-and)))
                     left)))
             (parse-cmp ()
               (let ((left (parse-add)))
                 (if (member (peek) '(:eq :ne :lt :gt :le :ge))
                     (let ((op (next)))
                       `(,op ,left ,(parse-add)))
                     left)))
             (parse-add ()
               (let ((left (parse-unary)))
                 (if (eq (peek) :mod)
                     (progn (next) `(:mod ,left ,(parse-unary)))
                     left)))
             (parse-unary ()
               (cond
                 ((eq (peek) :not)
                  (next) (eat :lparen)
                  (prog1 `(:not ,(parse-or)) (eat :rparen)))
                 (t (parse-primary))))
             (parse-primary ()
               (let ((tok (peek)))
                 (cond
                   ((eq tok :lparen)
                    (next)
                    (prog1 (parse-or) (eat :rparen)))
                   ((and (consp tok) (eq (first tok) :var))
                    (next)
                    (unless (string-equal (second tok) "value")
                      (error 'xpath-error
                             :message (format nil "unknown variable $~A" (second tok))))
                    '(:value))
                   ((and (consp tok) (eq (first tok) :attr))
                    (next) `(:attr ,(second tok)))
                   ((and (consp tok) (eq (first tok) :string))
                    (next) `(:lit ,(second tok)))
                   ((and (consp tok) (eq (first tok) :number))
                    (next) `(:lit ,(second tok)))
                   ((name-of tok)
                    (let ((name (second (next))))
                      (if (eq (peek) :lparen)
                          (progn
                            (next)
                            (let ((arg (if (eq (peek) :rparen)
                                           nil
                                           (parse-or))))
                              (eat :rparen)
                              (cond
                                ((string-equal name "count")
                                 `(:count ,arg))
                                ((string-equal name "string-length")
                                 `(:string-length ,(or arg '(:value))))
                                ((string-equal name "exists")
                                 `(:exists ,arg))
                                ((string-equal name "not")
                                 `(:not ,arg))
                                (t (error 'xpath-error
                                          :message (format nil "unknown function ~A" name))))))
                          `(:path ,name))))
                   (t (error 'xpath-error
                             :message (format nil "bad primary ~S" tok)))))))
      (let ((ast (parse-or)))
        (when (< pos (length toks))
          (error 'xpath-error :message (format nil "trailing tokens in ~S" string)))
        ast))))

(defun xpath-atom (value)
  (cond
    ((null value) nil)
    ((eq value :null) nil)
    ((array-p value) (if (plusp (length value)) (aref value 0) nil))
    ((and (listp value) (not (keywordp (first value))) (consp (first value)))
     (cdr (first value)))
    (t value)))

(defun xpath-lookup (env name)
  (let ((item (first env)))
    (cond
      ((hash-table-p item)
       (or (gethash name item)
           (gethash (stringify-key name) item)))
      (t nil))))

(defun xpath-truthy (value)
  (cond
    ((null value) nil)
    ((eq value :null) nil)
    ((eq value t) t)
    ((and (stringp value) (string= value "")) nil)
    ((and (realp value) (zerop value)) nil)
    ((and (array-p value) (zerop (length value))) nil)
    (t t)))

(defun xpath-number (value)
  (let ((v (xpath-atom value)))
    (or (as-number v)
        (and (stringp v) (as-number v)))))

(defun xpath-string (value)
  (as-string (xpath-atom value)))

(defun xpath-cmp (op a b)
  (let ((na (xpath-number a))
        (nb (xpath-number b))
        (sa (xpath-string a))
        (sb (xpath-string b)))
    (ecase op
      (:eq (or (and (realp na) (realp nb) (= na nb))
               (and sa sb (string= sa sb))
               (equal a b)))
      (:ne (not (xpath-cmp :eq a b)))
      ((:lt :gt :le :ge)
       (when (and na nb)
         (ecase op
           (:lt (< na nb))
           (:gt (> na nb))
           (:le (<= na nb))
           (:ge (>= na nb))))))))

(defun xpath-eval (ast env)
  (if (atom ast)
      ast
      (ecase (first ast)
        (:or (or (xpath-truthy (xpath-eval (second ast) env))
                 (xpath-truthy (xpath-eval (third ast) env))))
        (:and (and (xpath-truthy (xpath-eval (second ast) env))
                   (xpath-truthy (xpath-eval (third ast) env))))
        (:not (not (xpath-truthy (xpath-eval (second ast) env))))
        (:value (xpath-atom (first env)))
        (:path (xpath-lookup env (second ast)))
        (:attr (xpath-lookup env (second ast)))
        (:lit (second ast))
        (:count
         (let ((v (xpath-eval (second ast) env)))
           (cond
             ((array-p v) (length v))
             ((and (listp v) (not (keywordp (first v)))) (length v))
             ((null v) 0)
             (t 1))))
        (:string-length
         (length (or (xpath-string (xpath-eval (second ast) env)) "")))
        (:exists (xpath-truthy (xpath-eval (second ast) env)))
        (:mod
         (let ((a (xpath-number (xpath-eval (second ast) env)))
               (b (xpath-number (xpath-eval (third ast) env))))
           (and a b (not (zerop b)) (mod a b))))
        ((:eq :ne :lt :gt :le :ge)
         (xpath-cmp (first ast)
                    (xpath-eval (second ast) env)
                    (xpath-eval (third ast) env))))))

(defun xpath-true-p (test value)
  "Evaluate XSD 1.1 test XPath against VALUE (hash-table or atomic). NIL test → T."
  (when (or (null test) (string= test ""))
    (return-from xpath-true-p t))
  (handler-case
      (xpath-truthy (xpath-eval (xpath-parse test) (list value)))
    (error () nil)))

(defun parse-alternative-test (test)
  "TEST like \"kind = 'circ'\" → (values property value) or NIL."
  (when (and test (plusp (length test)))
    (handler-case
        (let ((ast (xpath-parse test)))
          (when (and (consp ast) (member (first ast) '(:eq)))
            (let ((left (second ast))
                  (right (third ast)))
              (when (and (consp left) (member (first left) '(:path :attr))
                         (consp right) (eq (first right) :lit))
                (values (second left) (second right))))))
      (xpath-error () nil))))
